// 'use client'
import { Inter } from "next/font/google";
import "../css/globals.css";
import "../css/custom/admin.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Link from "next/link";

// import "bootstrap/dist/js/bootstrap.bundle.min.js";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "TopUpin.ID",
    description: "Generated by create next app",
};

export default function AdminLayout({ children }) {

    return (
        <html lang="en">
            <body className={inter.className}>

                <div className="container-admin">

                    <div className="navbar-admin">
                        <div className="container-innner">
                            <div className="logo">
                                <div className="navbar-brand-admin">
                                    TopUpin.ID
                                </div>
                                <div className="user-login">
                                    Nasrul Hakim
                                </div>
                            </div>
                        </div>
                    </div>

                    <div className="container-wrapper-admin">
                        <div className="section-left">
                            <div className="menu">
                                <div className="title-menu">
                                    <div className="text">
                                        Home
                                    </div>
                                </div>
                                <div className="title-menu">
                                    <div className="text">
                                        Digiflaz
                                    </div>
                                    <div className="subMenu">
                                        <Link href="/admin/digiflazz" className="no-decoration text-white"> Produk Dari Digiflazz </Link>
                                    </div>
                                    <div className="subMenu">
                                        Sub Menu 2
                                    </div>
                                    <div className="subMenu">
                                        Sub Menu 3
                                    </div>
                                </div>
                                <div className="title-menu">
                                    <div className="text">
                                        Database PPOB
                                    </div>
                                    <div className="subMenu">
                                        <Link href="/admin/produk_publish/all_produk" className="no-decoration text-white">Produk Publish</Link>
                                    </div>
                                    <div className="subMenu">
                                        Voucher Setting
                                    </div>
                                </div>

                                <div className="title-menu">
                                    <div className="text">
                                        Layout Setting
                                    </div>
                                    <div className="subMenu">
                                        Banner
                                    </div>
                                    <div className="subMenu">
                                        Deskripsi Setting
                                    </div>
                                </div>

                                <div className="title-menu">
                                    <div className="text">
                                        Transaksi
                                    </div> 
                                </div>
                                
                                <div className="title-menu">
                                    <div className="text">
                                        User
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="section-right">
                            {children}
                        </div>
                    </div>

                </div>
            </body>
        </html>
    );
}
