import { Inter } from "next/font/google";
import "../css/globals.css";
import "../css/custom/style.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Link from "next/link";
// import "bootstrap/dist/js/bootstrap.bundle.min.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "TopUpin.ID",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <div className="container-custom">

          <div className="navbar-custom">
            <div className="logo">
              <div className="navbar-brand-custom">
                TopUpin.ID
              </div>
            </div>
          </div>

          <div className="carousell-custom">
            Ini Adalah Gambar Carousell
          </div>

          <div className="menu">
            <div className="list-menu active">
              <Link href="/" className="no-decoration">
                Dashboard
              </Link>
            </div>
            <div className="list-menu">
              <Link href="/categori/pulsa" className="no-decoration">
                Pulsa
              </Link>
            </div>
            <div className="list-menu">
              <Link href="/categori/paketData" className="no-decoration">
                Paket Data
              </Link>
            </div>
            <div className="list-menu">
              <Link href="/categori/game" className="no-decoration">
                Game
              </Link>
            </div>
          </div>

          <div className="container-wrapper">
            {children}
          </div>

          <div className="footer-custom">
            <div className="content">
              Ini Adalah Footer
            </div>
          </div>

        </div>
      </body>
    </html>
  );
}
